<h1><?php echo $this->message; ?></h1>
<?php
    if (isset($this->userName)){
        echo "<h3>$this->userName</h3>";
        echo "<h3>$this->age</h3>";
        echo "<h3>$this->email</h3>";
    }

    ?>

<form method="post" action="/">
    <div class="form-group">
        <label>User Name</label>
        <input type="text" class="form-control" id="exampleInputEmail1" placeholder="User Name" name="userName">
    </div>
    <div class="form-group">
        <label>Email</label>
        <input type="email" class="form-control" placeholder="Email" name="email">
    </div>
    <div class="form-group">
        <label>Age</label>
        <input type="text" class="form-control" placeholder="Age" name="age">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>